#!/bin/bash

# ==========================================
# BitZen Backend - Supabase Quick Setup
# ==========================================

set -e  # Exit on error

echo "╔════════════════════════════════════════╗"
echo "║  BitZen Backend - Supabase Setup      ║"
echo "╚════════════════════════════════════════╝"
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled. Please update .env manually."
        exit 1
    fi
fi

echo "📋 Step 1: Collecting Supabase credentials..."
echo ""

# Prompt for Supabase details
read -p "Enter your Supabase DATABASE_URL: " DATABASE_URL
read -p "Enter your Supabase Project URL (https://xxx.supabase.co): " SUPABASE_URL
read -p "Enter your Supabase ANON key: " SUPABASE_ANON_KEY

# Extract DB details from DATABASE_URL
if [[ $DATABASE_URL =~ postgresql://([^:]+):([^@]+)@([^:]+):([^/]+)/(.+) ]]; then
    DB_USER="${BASH_REMATCH[1]}"
    DB_PASSWORD="${BASH_REMATCH[2]}"
    DB_HOST="${BASH_REMATCH[3]}"
    DB_PORT="${BASH_REMATCH[4]}"
    DB_NAME="${BASH_REMATCH[5]}"
    echo "✅ Database credentials parsed successfully"
else
    echo "⚠️  Could not parse DATABASE_URL automatically"
    read -p "Enter DB_HOST: " DB_HOST
    read -p "Enter DB_PASSWORD: " DB_PASSWORD
    DB_USER="postgres"
    DB_PORT="5432"
    DB_NAME="postgres"
fi

echo ""
echo "🔐 Step 2: Generating JWT secrets..."

# Generate JWT secrets
JWT_SECRET=$(openssl rand -base64 32)
JWT_REFRESH_SECRET=$(openssl rand -base64 32)
echo "✅ JWT secrets generated"

echo ""
echo "📝 Step 3: Creating .env file..."

# Create .env file
cat > .env << EOF
# ==========================================
# GENERATED BY setup-supabase.sh
# Date: $(date)
# ==========================================

# Environment
NODE_ENV=development

# Server
PORT=3001
API_VERSION=v1

# Supabase Database
DATABASE_URL=${DATABASE_URL}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}

# Supabase API
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

# Redis (Optional - comment out for hackathon)
# REDIS_URL=redis://localhost:6379
REDIS_HOST=localhost
REDIS_PORT=6379

# JWT Authentication
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRE=7d
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_REFRESH_EXPIRE=30d

# Starknet Configuration
STARKNET_NETWORK=sepolia
STARKNET_RPC_URL=https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_9/YOUR_ALCHEMY_KEY
STARKNET_PRIVATE_KEY=YOUR_PRIVATE_KEY

# Deployed Contracts (Starknet Sepolia)
ZKPASSPORT_ADDRESS=0x04de9778b76c309cf3780e65c87060b046ba88574a950ef1d399e9b6fcd1b44d
SERVICE_REGISTRY_ADDRESS=0x06b3b6f139090875372d25adfa8401c50474a05aeb8e4c1d0365601563aa32da
AGENT_ACCOUNT_CLASS_HASH=0x12ccc0cdeddc1eea432f376c78dca4d54db8bd0de66b3e150ecfb9d5cf47f00

# Security
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# CORS
CORS_ORIGIN=http://localhost:3000,http://localhost:3001

# Logging
LOG_LEVEL=debug
LOG_FILE=logs/app.log
EOF

echo "✅ .env file created"

echo ""
echo "🗄️  Step 4: Checking database tables..."
echo ""
echo "⚠️  IMPORTANT: You need to create tables in Supabase!"
echo ""
echo "Two options:"
echo ""
echo "Option 1 (Recommended): Run SQL in Supabase Dashboard"
echo "  1. Open Supabase Dashboard → SQL Editor"
echo "  2. Copy contents of 'supabase-schema.sql'"
echo "  3. Paste and click 'Run'"
echo ""
echo "Option 2: Let backend auto-create tables"
echo "  1. Just run 'npm run dev'"
echo "  2. Tables will be created automatically"
echo ""

read -p "Have you already run the SQL schema in Supabase? (y/N): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "✅ Great! Tables should be ready."
else
    echo "⚠️  Remember to create tables before using the API!"
    echo "   File: supabase-schema.sql"
fi

echo ""
echo "📦 Step 5: Installing dependencies..."

if [ ! -d "node_modules" ]; then
    npm install
    echo "✅ Dependencies installed"
else
    echo "✅ Dependencies already installed"
fi

echo ""
echo "🎯 Step 6: Testing database connection..."

# Create a simple test script
cat > test-db-connection.js << 'EOF'
const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

(async () => {
  try {
    const result = await pool.query('SELECT NOW()');
    console.log('✅ Database connection successful!');
    console.log('   Server time:', result.rows[0].now);
    
    // Check if tables exist
    const tables = await pool.query(`
      SELECT tablename 
      FROM pg_tables 
      WHERE schemaname = 'public' 
      ORDER BY tablename
    `);
    
    if (tables.rows.length > 0) {
      console.log('\n✅ Found', tables.rows.length, 'tables:');
      tables.rows.forEach(row => console.log('   -', row.tablename));
    } else {
      console.log('\n⚠️  No tables found. Please run supabase-schema.sql');
    }
    
    await pool.end();
  } catch (error) {
    console.error('❌ Database connection failed:', error.message);
    process.exit(1);
  }
})();
EOF

node test-db-connection.js
rm test-db-connection.js

echo ""
echo "╔════════════════════════════════════════╗"
echo "║  Setup Complete! 🎉                   ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo ""
echo "1. Update Starknet credentials in .env:"
echo "   - STARKNET_RPC_URL (get from Alchemy)"
echo "   - STARKNET_PRIVATE_KEY (your wallet)"
echo ""
echo "2. Start the development server:"
echo "   npm run dev"
echo ""
echo "3. Test the API:"
echo "   curl http://localhost:3001/health"
echo ""
echo "4. View API documentation:"
echo "   cat API_DOCS.md"
echo ""
echo "Happy hacking! 🚀"
echo ""
